# Generated by Django 4.2.5 on 2023-10-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activitytype',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('fabricant', models.IntegerField()),
                ('fournisseur', models.IntegerField()),
                ('bureauachat', models.IntegerField(db_column='bureauAchat')),
                ('commercial', models.IntegerField()),
                ('gouvernementale', models.IntegerField()),
                ('autre', models.IntegerField()),
            ],
            options={
                'db_table': 'ActivityType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=191)),
                ('city', models.CharField(max_length=191)),
                ('state', models.CharField(max_length=191)),
                ('country_name', models.CharField(max_length=191)),
                ('country_code', models.CharField(max_length=191)),
                ('postalcode', models.CharField(db_column='postalCode', max_length=191)),
            ],
            options={
                'db_table': 'Address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Businesscard',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': 'BusinessCard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=191)),
                ('last_name', models.CharField(max_length=191)),
                ('annual_purchase_amount', models.IntegerField()),
            ],
            options={
                'db_table': 'Buyer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191, unique=True)),
                ('description', models.CharField(max_length=191)),
            ],
            options={
                'db_table': 'Category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('certificateholder', models.CharField(db_column='certificateHolder', max_length=191)),
                ('certificatenum', models.CharField(db_column='certificateNum', max_length=191)),
                ('certificatename', models.CharField(db_column='certificateName', max_length=191)),
                ('certificateemissiondate', models.DateTimeField(db_column='certificateEmissionDate')),
                ('certificateexpirationdate', models.DateTimeField(db_column='certificateExpirationDate')),
                ('certificateimages', models.CharField(db_column='certificateImages', max_length=191)),
                ('licenseholder', models.CharField(blank=True, db_column='licenseHolder', max_length=191, null=True)),
                ('licensenum', models.CharField(blank=True, db_column='licenseNum', max_length=191, null=True)),
                ('licensename', models.CharField(blank=True, db_column='licenseName', max_length=191, null=True)),
                ('licenseemissiondate', models.DateTimeField(blank=True, db_column='licenseEmissionDate', null=True)),
                ('licenseexpirationdate', models.DateTimeField(blank=True, db_column='licenseExpirationDate', null=True)),
                ('licenseimages', models.CharField(blank=True, db_column='licenseImages', max_length=191, null=True)),
            ],
            options={
                'db_table': 'Certificate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('blockedby', models.CharField(db_column='blockedBy', max_length=191)),
                ('blocked', models.IntegerField()),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('lastmessage', models.CharField(db_column='lastMessage', max_length=191)),
                ('lastvieweduser1', models.DateTimeField(db_column='lastViewedUser1')),
                ('lastvieweduser2', models.DateTimeField(db_column='lastViewedUser2')),
                ('lastskipuser1', models.DateTimeField(db_column='lastSkipUser1')),
                ('lastskipuser2', models.DateTimeField(db_column='lastSkipUser2')),
            ],
            options={
                'db_table': 'Chat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=191, null=True)),
                ('company_type', models.CharField(max_length=191)),
                ('description', models.CharField(max_length=191)),
                ('marchevise', models.CharField(db_column='marcheVise', max_length=191)),
                ('password', models.CharField(blank=True, max_length=191, null=True)),
                ('phone', models.CharField(blank=True, max_length=191, null=True)),
                ('fax', models.CharField(max_length=191)),
                ('creationyear', models.IntegerField(db_column='creationYear')),
                ('website', models.CharField(max_length=191)),
                ('logo', models.CharField(max_length=191)),
                ('companyimages', models.CharField(db_column='companyImages', max_length=191)),
                ('companyvideos', models.CharField(db_column='companyVideos', max_length=191)),
                ('employersnumber', models.CharField(db_column='employersNumber', max_length=191)),
                ('registerdate', models.DateTimeField(db_column='registerDate')),
            ],
            options={
                'db_table': 'Company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contactstatus',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=191)),
            ],
            options={
                'db_table': 'ContactStatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exportationcapacity',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('exportationstartyear', models.IntegerField(db_column='exportationStartYear')),
                ('principalmarketsanddistribution', models.JSONField(db_column='principalMarketsAndDistribution')),
                ('shippingconditions', models.JSONField(db_column='shippingConditions')),
                ('accepteddevise', models.JSONField(db_column='acceptedDevise')),
                ('paymenttypes', models.JSONField(db_column='paymentTypes')),
                ('language', models.JSONField(db_column='Language')),
            ],
            options={
                'db_table': 'ExportationCapacity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exposition',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('exponame', models.CharField(db_column='expoName', max_length=191)),
                ('description', models.CharField(max_length=191)),
                ('pays', models.JSONField()),
                ('exposyear', models.IntegerField(db_column='exposYear')),
                ('expoimages', models.CharField(db_column='expoImages', max_length=191)),
                ('index', models.IntegerField()),
            ],
            options={
                'db_table': 'Exposition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fabricationprocess',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('processname', models.CharField(db_column='processName', max_length=191)),
                ('processdescription', models.CharField(db_column='processDescription', max_length=191)),
                ('processimages', models.CharField(db_column='processImages', max_length=191)),
                ('index', models.IntegerField()),
            ],
            options={
                'db_table': 'FabricationProcess',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('factoryaddress', models.CharField(db_column='factoryAddress', max_length=191)),
                ('factorysize', models.CharField(db_column='factorySize', max_length=191)),
                ('productionlinesnumb', models.FloatField(blank=True, db_column='productionLinesNumb', null=True)),
                ('annualproductionvalue', models.FloatField(blank=True, db_column='annualProductionValue', null=True)),
                ('factoryimages', models.CharField(blank=True, db_column='factoryImages', max_length=191, null=True)),
                ('factoryvideos', models.CharField(blank=True, db_column='factoryVideos', max_length=191, null=True)),
            ],
            options={
                'db_table': 'Factory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191, unique=True)),
            ],
            options={
                'db_table': 'Keyword',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=191)),
                ('content', models.CharField(max_length=191)),
                ('fileurl', models.CharField(blank=True, db_column='fileUrl', max_length=191, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'Message',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=191)),
                ('content', models.CharField(max_length=191)),
                ('notificationurl', models.CharField(blank=True, db_column='notificationUrl', max_length=191, null=True)),
                ('imageurl', models.CharField(blank=True, db_column='imageUrl', max_length=191, null=True)),
                ('read', models.IntegerField()),
                ('createdat', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': 'Notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrismaMigrations',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('checksum', models.CharField(max_length=64)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('migration_name', models.CharField(max_length=255)),
                ('logs', models.TextField(blank=True, null=True)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('applied_steps_count', models.PositiveIntegerField()),
            ],
            options={
                'db_table': '_prisma_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('productname', models.CharField(db_column='productName', max_length=191)),
                ('marchevise', models.CharField(db_column='marcheVise', max_length=191)),
                ('marque', models.CharField(max_length=191)),
                ('fabricationdate', models.DateTimeField(db_column='fabricationDate')),
                ('madein', models.CharField(db_column='madeIn', max_length=191)),
                ('modelnumber', models.CharField(db_column='modelNumber', max_length=191)),
                ('groupe', models.CharField(max_length=191)),
                ('certifications', models.JSONField()),
                ('currency', models.CharField(max_length=191)),
                ('paymentmethod', models.JSONField(db_column='paymentMethod')),
                ('details', models.CharField(max_length=191)),
                ('product_thumbnail_reference', models.CharField(max_length=191)),
                ('productsphotos', models.CharField(db_column='productsPhotos', max_length=1000)),
                ('productsvideos', models.CharField(db_column='productsVideos', max_length=1000)),
                ('fixationprice', models.CharField(db_column='fixationPrice', max_length=191)),
                ('modelogistique', models.JSONField(db_column='modeLogistique')),
                ('port', models.CharField(max_length=191)),
                ('descriptionemballage', models.CharField(db_column='descriptionEmballage', max_length=191)),
                ('imagesemballage', models.CharField(db_column='imagesEmballage', max_length=191)),
                ('termsandconditions', models.IntegerField(db_column='termsAndConditions')),
                ('productinformations', models.CharField(db_column='productInformations', max_length=191)),
                ('minquantity', models.CharField(db_column='minQuantity', max_length=191)),
                ('verified', models.IntegerField()),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('rupturestock', models.IntegerField(db_column='ruptureStock')),
            ],
            options={
                'db_table': 'Product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productkeyword',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ProductKeyword',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Quantityfabrication',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('quantity', models.CharField(max_length=191)),
                ('unity', models.CharField(max_length=191)),
                ('par', models.CharField(max_length=191)),
            ],
            options={
                'db_table': 'QuantityFabrication',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Quantitylivraison',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('quantity', models.CharField(max_length=191)),
                ('livraison', models.CharField(max_length=191)),
            ],
            options={
                'db_table': 'QuantityLivraison',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Quantityprice',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('quantity', models.CharField(max_length=191)),
                ('price', models.FloatField()),
                ('solde', models.IntegerField()),
                ('soldeprice', models.FloatField(blank=True, db_column='soldePrice', null=True)),
            ],
            options={
                'db_table': 'QuantityPrice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=191)),
                ('shipping_rating', models.FloatField()),
                ('productquality_rating', models.FloatField(db_column='productQuality_rating')),
                ('salesservices_rating', models.FloatField(db_column='salesServices_rating')),
                ('createddate', models.DateTimeField(db_column='createdDate')),
            ],
            options={
                'db_table': 'Review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191, unique=True)),
            ],
            options={
                'db_table': 'Sector',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sectorsincompany',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'SectorsInCompany',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191, unique=True)),
                ('description', models.CharField(max_length=191)),
            ],
            options={
                'db_table': 'Subcategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='firstName', max_length=191)),
                ('lastname', models.CharField(db_column='lastName', max_length=191)),
                ('companyname', models.CharField(db_column='companyName', max_length=191)),
                ('email', models.CharField(max_length=191, unique=True)),
                ('password', models.CharField(max_length=191)),
                ('phone', models.CharField(max_length=191)),
                ('countryname', models.CharField(db_column='countryName', max_length=191)),
                ('countrycode', models.CharField(db_column='countryCode', max_length=191)),
                ('role', models.IntegerField()),
                ('verifiedemail', models.IntegerField(db_column='verifiedEmail')),
                ('completedcompanyprofile', models.IntegerField(db_column='completedCompanyProfile')),
                ('completedfactory', models.IntegerField(db_column='completedFactory')),
                ('completedexportation', models.IntegerField(db_column='completedExportation')),
                ('completedcertification', models.IntegerField(db_column='completedCertification')),
                ('subscription', models.CharField(max_length=191)),
                ('authprovider', models.CharField(db_column='authProvider', max_length=191)),
                ('blocked', models.IntegerField()),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usercontacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': '_UserContacts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('verified', models.IntegerField()),
            ],
            options={
                'db_table': 'Vendor',
                'managed': False,
            },
        ),
    ]
